---
language: python
python: "2.7"

before_install:
  - sudo apt-get update -qq

install:
  - pip install ansible

script:
  # check the syntax playbook
  - ansible-playbook -i inventory test.yml --syntax-check

  # run the playbook with ansible-playbook
  - "ansible-playbook -i inventory test.yml --connection=local --sudo"

  # run again, checking it's idempotent
  - >
    ansible-playbook -i inventory test.yml --connection=local --sudo
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
